

services:
  postgres:
      image: postgres:15
      container_name: merchant-postgres
      restart: always
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: password
        POSTGRES_DB: merchant_platform
      ports:
        - "5432:5432"
  redis:
    image: redis:7
    container_name: merchant-redis
    ports:
      - "6381:6379"
      - "6382:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: merchant-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

