export const SERVICE_NAMES = {
  API_GATEWAY: "API_GATEWAY",
  AUTH_SERVICE: "AUTH_SERVICE",
  TRANSACTION_SERVICE: "TRANSACTION_SERVICE",
  FRAUD_SERVICE: "FRAUD_SERVICE",
};

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
};
